# Generated by Django 3.2.8 on 2021-11-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='posts',
            name='posts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_blog.category'),
            preserve_default=False,
        ),
    ]
