# Generated by Django 3.2.8 on 2021-11-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0004_auto_20211128_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='posts',
        ),
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_blog.category'),
            preserve_default=False,
        ),
    ]
