# Generated by Django 3.2.8 on 2021-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0005_auto_20211128_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=10),
        ),
    ]
